POST http://localhost:8080/checkouts
Content-Type: application/json

{
  "line_items": [
    {
      "price_data": {
        "currency": "INR",
        "unit_amount": "500",
        "product_data": {
          "name": "hat",
          "images": [

          ]
        }
      },
      "quantity": 2
    }
  ]
}


###

POST http://localhost:8080/payments
Content-Type: application/json

{
  "amount": 100
}
